[package]
name = "diar"
version = "0.1.0"
authors = ["index197511"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.27"
clap = "2.31"
failure = "0.1"
