[package]
name = "diar"
version = "2.1.1"
authors = ["index197511", "4afS"]
edition = "2018"
license = "MIT"
description = "A directory favorite tool in rust"
repository = "https://github.com/Index197511/diar"
readme = "README.md"
keywords = ["directory", "bookmark", "rust"]

[dependencies]
sled = "0.27"
clap = "2.31"
dirs = "2.0.2"
